--c18
SELECT NT,COUNT(*)SOSACH
FROM SACH
GROUP BY NT
ORDER BY NT;
--C17
SELECT TACGIA, COUNT(*) SOTP 
FROM TACPHAM
GROUP BY TACGIA;

-- C16
SELECT T.NT,TUA, COUNT(*)SOSACH
FROM SACH S JOIN TACPHAM T ON T.NT=S.NT
GROUP BY T.NT, TUA HAVING COUNT(*)>=2
ORDER BY T.nt;
--C19
SELECT ND, EXTRACT(YEAR FROM NGAYMUON) NAM,COUNT(*) SOLANMUON
FROM MUON
GROUP BY ND, EXTRACT(YEAR FROM NGAYMUON)
ORDER BY ND, EXTRACT(YEAR FROM NGAYMUON);
--C20
 CREATE TABLE C20 AS
    SELECT T.NT,TUA, COUNT(*)SOSACH
    FROM SACH S JOIN TACPHAM T ON T.NT=S.NT
    GROUP BY T.NT, TUA HAVING COUNT(*)>=2
    ORDER BY T.nt;
SELECT * 
FROM C20
WHERE SOSACH = (SELECT MAX(SOSACH)FROM C20);

DROP TABLE C20;
--c23
SELECT COUNT(*)
FROM
        (SELECT TACGIA, COUNT(*) SOTP 
        FROM TACPHAM
        GROUP BY TACGIA HAVING COUNT(*)>1);
--C24
  CREATE TABLE C24 AS
        SELECT TUA, COUNT(DISTINCT ND) SODG
        FROM TACPHAM T JOIN SACH S ON T.NT=S.NT
                JOIN MUON M ON M.NS=S.NS
        GROUP BY TUA;
SELECT * 
FROM C24
WHERE SODG = (SELECT MAX(SODG)FROM C24);

--C28
SELECT TUA
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT  
                LEFT JOIN MUON M ON M.NS=S.NS
WHERE NGAYMUON IS NULL
ORDER BY NT ;

SELECT TUA
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT 
WHERE NS NOT IN (SELECT NS FROM MUON)
ORDER BY T.NT ;
--C29
SELECT TUA 
FROM TACPHAM
WHERE NT not in (SELECT NT
                FROM  SACH S LEFT JOIN MUON M ON M.NS=S.NS
                WHERE NGAYMUON IS NULL);