/*
SELECT 
FROM
WHERE
GROUP BY
ORDER BY
*/
SELECT * 
FROM KHOAHOC;
--C2
SELECT * 
FROM HOCVIEN
WHERE gioitinh=0;
--C3 
SELECT * 
FROM HOCVIEN
WHERE DIACHI LIKE 'C¿n Tho%';

SELECT * 
FROM khoahoc
WHERE TENKH LIKE '_______';
-- c9
SELECT * 
FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH) BETWEEN 1998 AND 2000;

SELECT * 
FROM HOCVIEN
WHERE LEFT(TENHV,1) BETWEEN 'A' AND 'D';
-- C8
SELECT * 
FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH) =2001 AND EXTRACT(MONTH FROM NGAYSINH) =12 ;
--c4
SELECT L.*
FROM LOP L, KHOAHOC K
WHERE L.MAKH=K.MAKH AND TENKH='Khóa 1';

SELECT L.*
FROM LOP L JOIN KHOAHOC K ON L.MAKH=K.MAKH 
WHERE TENKH='Khóa 1';
-- c5
SELECT H.MAHV, TENHV
FROM LOP L JOIN KHOAHOC K ON L.MAKH=K.MAKH 
            JOIN PHIEUTHU P ON P.MALOP=L.MALOP
            JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TENKH='Khóa 1';

--C10
SELECT P.*
FROM PHIEUTHU P
WHERE NGAYLAPPHIEU BETWEEN '2021-06-05' AND '2021-06-10';
--  C11
SELECT H.*
FROM LOP L JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
            JOIN PHIEUTHU P ON P.MALOP=L.MALOP
            JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TENLOAI='Ti?ng Anh c?n b?n' AND TENLOP='L?p 1' ;
--C12
SELECT L.*
FROM LOP L JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
            JOIN CHUONGTRINH C ON C.MACT=LL.MACT
         
WHERE TENCT='Ti?ng Anh T?ng Quát';
--C15
SELECT COUNT(*) SOHV
FROM HOCVIEN;
-- C16
SELECT count(*)
FROM LOP L JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
            JOIN PHIEUTHU P ON P.MALOP=L.MALOP
            JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TENLOAI='Ti?ng Anh c?n b?n' AND TENLOP='L?p 1' ;
-- c17
SELECT SUM(THANHTIEN) TONGTHU
FROM LOP L JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
            JOIN PHIEUTHU P ON P.MALOP=L.MALOP
            JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TENLOAI='Ti?ng Anh c?n b?n' AND TENLOP='L?p 1' ;
--C19
--C15
SELECT MAX(DIEM) DIEMLN
FROM DIEM;
-- C16